name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print current directory
        run: pwd

      - name: List files in directory
        run: ls -la

      - name: Install dependencies
        run: npm install
        working-directory: demo-project  # ✅ ONLY if your project is in a subfolder named demo-project
